{
  description = "file as a single self-contained binary";

  nixConfig = {
    extra-substituters = [ "https://unpins.cachix.org" ];
    extra-trusted-public-keys = [ "unpins.cachix.org-1:DDaShjbZ8VvcqxeTcAU3kV9vxZQBlyb7V/uLBHfTynI=" ];
  };

  inputs.unpins-lib.url = "github:unpins/nix-lib";

  # magic.mgc (file's compiled magic database) is NOT compiled into the binary's
  # rodata. It rides the binary's single metadata/runtime ZIP at EOF
  # (withRuntimeData), zstd-compressed: the db is sparse and compresses ~31x
  # (~10.6 MB raw -> ~340 KB). file.c::load() reads it back through the unpin-vfs
  # self-EOF reader (vendored vfs.c + miniz + zstd, EXPLICIT api only, no
  # `ld --wrap`) and hands the buffer to magic_load_buffers. See
  # docs/runtime-data.md (Pattern 2) and unpin_magic.c.
  #
  # This replaces the older compiled-in-blob (embedded_magic.h via xxd), which
  # baked the raw 10.6 MB into the binary AND, for the mega multicall, into its
  # bitcode module. The ZIP overlay carries it compressed and is merged into the
  # mega exactly like the man pages.
  #
  # Windows (windowsBuild below) uses the SAME VFS path. mingw has no memfd, so
  # vfs.c runs in marker mode (-DUNPIN_VFS_WIN_MARKER): the explicit
  # unpin_vfs_open materialises magic.mgc to a temp file and hands back a CRT fd,
  # with NO win32_* `ld --wrap` layer (file has none -- the default win32 path
  # would reference __real_win32_open, which only a perl-class consumer defines).
  # This drops the 10.6 MB xxd blob from both the .exe and its bitcode module, so
  # the windows mega module folds to one external symbol exactly like Linux. The
  # marker #define is inert on Linux (_WIN32 undefined), so injectVfs is shared.
  #
  # file-mingw.patch (Windows): upstream cdf.h aliases `struct timespec` to
  # `struct timeval` on WIN32 as a legacy pre-mingw-w64 shim; modern mingw-w64
  # ships its own timespec with a 64-bit tv_sec while timeval's is 32-bit, so the
  # alias makes cdf_ctime(&ts.tv_sec, ...) a pointer-type mismatch. Remove it.
  #
  # Windows libgnurx note: nixpkgs's libgnurx only builds a DLL plus an import
  # library; even with --enable-static --disable-shared, libgnurx.a is just a
  # symlink to the import lib. Recompile regex.o into a real static archive via
  # `ar rcs` and drop the DLL artifacts so file.exe links statically.
  outputs = { self, unpins-lib }:
    let
      lib = unpins-lib.lib;

      # The mount root file's VFS serves from. Unique so a folded mega never
      # confuses it with any other package's runtime data. Must match the
      # -DUNPIN_VFS_ROOT passed to vfs.c AND the ZIP entry the magic db is staged
      # at (the db lands at ZIP-root "magic.mgc", served as "<root>/magic.mgc").
      vfsRoot = "/__unpin_filemagic__/";

      # The unique, slash-free middle of vfsRoot. On mingw vfs.c matches virtual
      # paths by strstr(path, marker) instead of the strict POSIX prefix, so a
      # backslash-mangled or drive-prefixed form still resolves. file always
      # constructs the literal "<vfsRoot>magic.mgc", so the strstr is exact here.
      vfsMarker = "__unpin_filemagic__";

      # The compiled magic database as a clean ZIP-root tree ({ magic.mgc }).
      # Taken from the build-host's NATIVE file (buildPackages): magic.mgc is a
      # data file generated by mkmagic from the ASCII Magdir/ tables -- it is
      # architecture-independent and identical across the static/cross builds, so
      # one cached native copy serves every arch and avoids an extra engine build
      # just to regenerate it. Same nixpkgs pin => same file version => format
      # matches our libmagic.
      magicDbFor = pkgs: pkgs.buildPackages.runCommand "file-magic-db" { } ''
        mkdir -p "$out"
        cp ${pkgs.buildPackages.file}/share/misc/magic.mgc "$out/magic.mgc"
      '';

      # Vendor the unpin-vfs core into file's build and link it into the `file`
      # binary so load() can read magic.mgc from the embedded ZIP. The objects
      # are precompiled with the right -D knobs (NOT via the autotools implicit
      # .c.o rule, which carries none of them) and injected through a file_LDADD
      # override; they are not in file_SOURCES/file_DEPENDENCIES, so make never
      # tries to rebuild them with the wrong flags. Shared by the Linux `build`
      # and the mingw `windowsBuild` (the marker #define below is inert on Linux).
      injectVfs = pkgs: drv: drv.overrideAttrs (old: {
        patches = (old.patches or [ ]) ++ [ ./file-vfs-magic.patch ];

        postPatch = (old.postPatch or "") + ''
          echo "==> inject unpin-vfs core (self-EOF + zstd) for embedded magic.mgc"
          cp ${./vfs.c}          src/vfs.c
          cp ${./vfs.h}          src/vfs.h
          cp ${./miniz.c}        src/miniz.c
          cp ${./miniz.h}        src/miniz.h
          cp ${./unpin_zstd.c}   src/unpin_zstd.c
          cp ${./unpin_zstd.h}   src/unpin_zstd.h
          cp ${./zstddeclib.c}   src/zstddeclib.c
          cp ${./unpin_magic.c}  src/unpin_magic.c
          cp ${./unpin_magic.h}  src/unpin_magic.h
        '';

        # Precompile the VFS objects with the build's $CC (the engine cc-wrapper
        # -> -flto bitcode under engine = "unpin-llvm", so they fold into the
        # multicall module like the rest of file's objects). Then queue the
        # file_LDADD override (in an array so the spaces survive).
        preBuild = (old.preBuild or "") + ''
          echo "==> precompile unpin-vfs objects for file"
          ( cd src
            MZ='-DMINIZ_USE_ZSTD -DMINIZ_NO_TIME -DMINIZ_NO_ARCHIVE_WRITING_APIS -DMINIZ_NO_ZLIB_APIS -DMINIZ_NO_ZLIB_COMPATIBLE_NAMES'
            $CC $CFLAGS -c -I. \
              -DUNPIN_VFS_SELF -DUNPIN_VFS_ROOT='"${vfsRoot}"' -DMINIZ_USE_ZSTD \
              -DUNPIN_VFS_WIN_MARKER='"${vfsMarker}"' \
              vfs.c -o vfs.o
            $CC $CFLAGS -c -I. $MZ -w miniz.c -o miniz.o
            $CC $CFLAGS -c -I. -DMINIZ_USE_ZSTD -DUNPIN_ZSTD_VENDORED -w unpin_zstd.c -o unpin_zstd.o
            $CC $CFLAGS -c -I. -DUNPIN_VFS_ROOT='"${vfsRoot}"' unpin_magic.c -o unpin_magic.o
          )
          makeFlagsArray+=("file_LDADD=libmagic.la vfs.o miniz.o unpin_zstd.o unpin_magic.o${if pkgs.stdenv.hostPlatform.isDarwin then "" else " -lm"}")
        '';

        # magic.mgc now rides the embedded ZIP, not the binary's rodata and not
        # $out/share/misc -- drop the on-disk copy so the install stays single-file.
        postInstall = (old.postInstall or "") + ''
          rm -rf $out/share/misc
        '';
      });
    in
    lib.mkStandaloneFlake {
      inherit self;
      name = "file";

      # Fold `file` into the busybox-style mega through the unpin-llvm engine:
      # the build emits a bitcode multicall module (one program, no applets).
      # The VFS objects ride in as part of file's link (captured via
      # inferLinkInputs); `runtimeDataRoot` points the mega at the magic db tree
      # so mkMegaMulticall merges it into the mega's ZIP (like the man pages).
      engine = "unpin-llvm";
      multicall = {
        inferLinkInputs = true;
        programs = [{ name = "file"; }];
        runtimeDataRoot = pkgs: "${magicDbFor pkgs}";
        # The mingw build uses the same VFS path as Linux (marker mode), so the
        # bitcode module folds to a single external (unpin__file__file_main) with
        # magic.mgc carried by the mega's ZIP, not a 10.6 MB compiled-in blob.
        windows = true;
        # And the darwin (Mach-O) mega: the engine emits a darwin module and the
        # magic.mgc rides the mega ZIP. vfs.c uses mkstemp (no memfd) on macOS;
        # the engine's libm stub resolves libmagic's -lm against libSystem.
        darwin = true;
      };

      build = pkgs:
        lib.withRuntimeData pkgs
          {
            primary = "file";
            stage = ''
              cp ${magicDbFor pkgs}/magic.mgc "$__unpin_stage/magic.mgc"
              chmod u+w "$__unpin_stage/magic.mgc"
            '';
          }
          (injectVfs pkgs (pkgs.pkgsStatic.file.overrideAttrs (old: {
            # On darwin, nix-lib's filterEnableStaticOnDarwin strips
            # --enable-static / --disable-shared to keep libSystem dynamic; file
            # doesn't need that and without --disable-shared we get a
            # libmagic.1.dylib next to the binary, breaking the single-binary
            # promise. Push --disable-shared back via the bash configureFlagsArray
            # so the (Nix-list) filter can't reach it.
            preConfigure = (old.preConfigure or "") + ''
              configureFlagsArray+=("--disable-shared" "--enable-static")
            '';
          })));

      windowsBuild = pkgs:
        let
          cross = lib.mingwStaticCross pkgs;
          libgnurxStatic = cross.windows.libgnurx.overrideAttrs (old: {
            # GCC 15 (nixpkgs 26.05) defaults to -std=gnu23, where `bool`, `true`,
            # `false` become keywords. libgnurx's vintage glibc regex
            # (regex_internal.h) still uses `bool` as a plain identifier, so the
            # C23 keyword makes regex.o fail. Pin the pre-C23 dialect.
            NIX_CFLAGS_COMPILE = (old.NIX_CFLAGS_COMPILE or "") + " -std=gnu17";
            # libgnurx's Makefile force-links libgnurx-0.dll even under
            # --disable-shared. The unpin-llvm engine's mingw CRT has no DLL
            # startup (DllMainCRTStartup), so that link fails before the old
            # postBuild could salvage a static archive. file links the regex
            # implementation statically anyway, so compile ONLY regex.o and ar it
            # into a real libgnurx.a — never reach the DLL target. (Also correct
            # for the gcc cross path, which otherwise wastes work on the DLL.)
            buildPhase = ''
              runHook preBuild
              make regex.o
              $AR rcs libgnurx.a regex.o
              runHook postBuild
            '';
            # nixpkgs' libgnurx postInstall symlinks `libgnurx.a` onto the import
            # lib; we install a REAL static archive instead, so clear it (else
            # the symlink collides: `ln: libgnurx.a: File exists`).
            postInstall = "";
            installPhase = ''
              runHook preInstall
              mkdir -p $out/lib $out/include
              install -m 644 libgnurx.a $out/lib/libgnurx.a
              install -m 644 regex.h $out/include/regex.h
              runHook postInstall
            '';
          });
        in
        # Same VFS path as Linux: magic.mgc rides the binary's EOF ZIP
        # (withRuntimeData) and load() reads it back through the unpin-vfs
        # self-EOF reader (marker mode on mingw). mkStandaloneFlake does NOT
        # auto-apply withRuntimeData on the windows chain (only withMan), so wrap
        # here just like the Linux `build` does. file-mingw.patch keeps the
        # timespec fix; injectVfs adds file-vfs-magic.patch + the VFS objects.
        lib.withRuntimeData pkgs
          {
            primary = "file";
            stage = ''
              cp ${magicDbFor pkgs}/magic.mgc "$__unpin_stage/magic.mgc"
              chmod u+w "$__unpin_stage/magic.mgc"
            '';
          }
          (injectVfs pkgs
            ((cross.file.override { libgnurx = libgnurxStatic; }).overrideAttrs (old: {
              patches = (old.patches or [ ]) ++ [ ./file-mingw.patch ];
              # -all-static: link the PE32+ fully static (no DLL imports beyond
              # the system CRT), matching the single-binary promise. The engine's
              # mingw CRT has no DLL startup, so anything else would fail to link.
              makeFlags = (old.makeFlags or [ ]) ++ [ "LDFLAGS=-all-static" ];
            })));
    };
}
